update

diff --git a/mambo b/mambo
--- a/mambo
+++ b/mambo
@@ -13,8 +13,9 @@ ENV_FILE_GENERATED="${STELLA_APP_ROOT}/.env"
 ENV_FILE_FOR_BASH_GENERATED="${STELLA_APP_ROOT}/env.bash"
 ENV_FILE_USER="${HOME}/mambo.env"
 
-# List of all services embedded that can be manipulated 
+# List of all services embedded that can be manipulated in command line
 MAMBO_SERVICES_LIST="traefik organizr2 ombi sabnzbd plex medusa tautulli"
+
 
 # MANAGE ENV VARIABLES AND FILES GENERATION -----------------
 __manage_env_and_files() {
@@ -110,7 +111,7 @@ __set_gpu_all() {
 __set_time_all() {
 	if [ -f "/etc/timezone" ]; then
 		TZ="$(cat /etc/timezone)"
-		yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "services.plex.environment[+]" "TZ=${TZ}"
+		yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "services.plex.environment[+]" "TZ=${TZ}"
 	fi
 	
 	__add_volume_for_time "organizr2"
@@ -124,13 +125,30 @@ __set_time_all() {
 
 
 __set_letsencrypt_service_all() {
+
+
 	case ${LETS_ENCRYPT} in
 		enable|debug )
 			for s in ${LETS_ENCRYPT_SERVICES}; do
 				__add_letsencrypt_service "${s}"
 			done
+
+			case ${LETS_ENCRYPT_CHALLENGE} in
+				HTTP )
+					yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "services.traefik.command[+]" "--certificatesresolvers.mambo.acme.httpchallenge=true"
+					yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "services.traefik.command[+]" "--certificatesresolvers.mambo.acme.httpchallenge.entrypoint=web_main"
+				;;
+				DNS )
+					yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "services.traefik.command[+]" "--certificatesresolvers.mambo.acme.dnschallenge=true"
+					yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "services.traefik.command[+]" "--certificatesresolvers.mambo.acme.dnschallenge.provider=${LETS_ENCRYPT_CHALLENGE_DNS_PROVIDER}"
+				;;
+			esac
+			
 		;;
 	esac
+
+	# set letsencrypt debug server if needed
+	[ "${LETS_ENCRYPT}" = "debug" ] && yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "services.traefik.command[+]" "--certificatesresolvers.mambo.acme.caserver=${LETS_ENCRYPT_SERVER_DEBUG}"
 }
 
 
@@ -171,7 +189,7 @@ __add_service_direct_port_access_all() {
 			port_inside="$(yq r docker-compose.yml services.$service.expose[0])"
 			if [ ! "${port_inside}" = "" ]; then
 				[ "${VERBOSE}" = "1" ] && echo "* Activate direct access to $service : mapping $port to $port_inside"
-				yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "services.$service.ports[+]" "$port:$port_inside"
+				yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "services.$service.ports[+]" "$port:$port_inside"
 			else
 				echo "* WARN : cannot activate direct access to $service through $port : Unknown inside port to map to. Inside port must be declared as first port in expose section."
 			fi
@@ -212,13 +230,13 @@ __add_gpu() {
 	done
 
 	if [ "${__opt_intel_quicksync}" = "1" ]; then
-		[ -d "/dev/dri" ] && yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "services.${__service}.devices[+]" "/dev/dri:/dev/dri"
+		[ -d "/dev/dri" ] && yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "services.${__service}.devices[+]" "/dev/dri:/dev/dri"
 	fi
 
 	if [ "${__opt_nvidia}" = "1" ]; then
-		yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "services.${__service}.environment[+]" "NVIDIA_VISIBLE_DEVICES=all"
-		yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "services.${__service}.environment[+]" "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility"
-		yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "services.${__service}.runtime" "nvidia"
+		yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "services.${__service}.environment[+]" "NVIDIA_VISIBLE_DEVICES=all"
+		yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "services.${__service}.environment[+]" "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility"
+		yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "services.${__service}.runtime" "nvidia"
 	fi
 }
 
@@ -234,7 +252,8 @@ __add_volume_for_time() {
 __add_letsencrypt_service() {
 	local __service="$1"
 
-	yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "services.${__service}.labels[+]" "traefik.http.routers.${__service}-secure.tls.certresolver=mambo"
+
+	yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "services.${__service}.labels[+]" "traefik.http.routers.${__service}-secure.tls.certresolver=mambo"
 }
 
 # declare an entrypoint to a service aswell to the secured version of the entrypoint
@@ -260,7 +279,7 @@ __set_redirect_https_service() {
 	local __service="$1"
 	
 	__service="${__service^^}"
-	local __var="${__service}_REDIRECT_HTTPS"
+	local __var="${__service}_REDIRECT_HTTPS_PRIORITY"
 
 	eval "export ${__var}=50"
 	__update_env_for_docker_compose "${__var}"
@@ -276,7 +295,7 @@ __add_volume_mapping_service() {
 	local __service="$1"
 	local __mapping="$2"
 
-	yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "services.${__service}.volumes[+]" "${__mapping}"
+	yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "services.${__service}.volumes[+]" "${__mapping}"
 
 }
 
@@ -284,10 +303,10 @@ __add_volume_local_definition() {
 	local __name="$1"
 	local __path="$2"
 
-	yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "volumes.${__name}.driver" "local"
-	yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "volumes.${__name}.driver_opts.type" "none"
-	yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "volumes.${__name}.driver_opts.o" "bind"
-	yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "volumes.${__name}.driver_opts.device" "${__path}"
+	yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "volumes.${__name}.driver" "local"
+	yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "volumes.${__name}.driver_opts.type" "none"
+	yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "volumes.${__name}.driver_opts.o" "bind"
+	yq w -i -- "${DOCKER_COMPOSE_FILE_GENERATED}" "volumes.${__name}.driver_opts.device" "${__path}"
 }
 
 
@@ -488,7 +507,7 @@ __xml_get_attribute_value() {
 }
 
 
-# Mambo mandatory root path
+# mambo mandatory root paths
 __set_mandatory_root_path_to_default() {
 	if [ "${MAMBO_DATA_PATH}" = "" ]; then
 	 	export MAMBO_DATA_PATH="${STELLA_APP_WORK_ROOT}/data"
@@ -505,7 +524,7 @@ __set_mandatory_root_path_to_default() {
 }
 
 
-# test if mandatory root path exists
+# test if mandatory root paths exists
 __check_mandatory_root_path() {
 	[ ! -d "${MAMBO_DATA_PATH}" ] && echo "* ERROR : Mandatory data root path [${MAMBO_DATA_PATH}] do not exist" && exit 1
 	[ ! -d "${MAMBO_DOWNLOAD_PATH}" ] && echo "* ERROR : Mandatory download root path [${MAMBO_DOWNLOAD_PATH}] do not exist" && exit 1
@@ -521,9 +540,11 @@ __check_mandatory_root_path() {
 __check_lets_encrypt_settings() {
  	case ${LETS_ENCRYPT} in
     	enable|debug ) 
-			[ "${LETS_ENCRYPT_MAIL}" = "" ] && echo "* ERROR : you have to specify a mail as identity into LETS_ENCRYPT_MAIL variable when using let's encrypt" && exit 1
-			[ "${MAMBO_DOMAIN}" = '.*' ] && echo "* ERROR : you cannot use a generic domain setted by MAMBO_DOMAIN when using let's encrypt" && exit 1
-			[ "${MAMBO_DOMAIN}" = "" ] && echo "* ERROR : you have to set a domain with  MAMBO_DOMAIN variable when using let's encrypt" && exit 1
+			[ "${LETS_ENCRYPT_MAIL}" = "" ] && echo "* ERROR : you have to specify a mail as identity into LETS_ENCRYPT_MAIL variable when using let's encrypt." && exit 1
+			[ "${MAMBO_DOMAIN}" = '.*' ] && echo "* ERROR : you cannot use a generic domain (.*) setted by MAMBO_DOMAIN when using let's encrypt. Set MAMBO_DOMAIN variables or --domain comand line option with other value." && exit 1
+			[ "${MAMBO_DOMAIN}" = "" ] && echo "* ERROR : you have to set a domain with MAMBO_DOMAIN variable or --domain comand line option when using let's encrypt." && exit 1
+			[ ! "${MAMBO_PORT_MAIN}" = "80" ] && echo "* ERROR : main area network HTTP port is not 80 but ${MAMBO_PORT_MAIN}. You need to use DNS challenge for let's encrypt. Set LETS_ENCRYPT_CHALLENGE* variables." && exit 1
+			[ ! "${MAMBO_PORT_MAIN_SECURE}" = "443" ] && echo "* ERROR : main area network HTTPS port is not 443 ${MAMBO_PORT_MAIN_SECURE}. You need to use DNS challenge for let's encrypt. Set LETS_ENCRYPT_CHALLENGE* variables" && exit 1
 		;;
 	esac
 }
@@ -545,13 +566,15 @@ usage() {
 
 # COMMAND LINE -----------------------------------------------------------------------------------
 PARAMETERS="
-DOMAIN=											'action' 			a				'info shell up down status install logs init restart' '1'
+ACTION=											'action' 			a				'info shell up down status install logs init restart' '1'
 TARGET=												'target' 					a				'${MAMBO_SERVICES_LIST}'	'0'
 "
 OPTIONS="
+DOMAIN='' 					'' 				'domain'				s 			0			''		  Mambo domain name.
 FILE='${ENV_FILE_USER}'				  		'f'				'path'					s			0		''					  User env site file (example : HOME/mambo.env).
-DAEMON=''				    'd'				''						b			0		''					  Daemon mode. When launching whole mambo, it is in daemon mode by default, but when launching a specific service, launch it in daemon mode.
+DEBUG='' 					'' 				''				b 			0			''		  Debug mode. More verbose and use lets encrypt debug server to not reach rate limit.
 VERBOSE=''				    'v'				''						b			0		''					  Verbose mode for debug purpose.
+DAEMON=''				    'd'				''						b			0		''					  Daemon mode. When launching whole mambo, it is in daemon mode by default, but when launching a specific service, launch it in daemon mode.
 PUID='$(id -u)' 			'u' 			'string'				s 			0			''		  user id - set MAMBO_USER_ID variable - will own bind mount created folder/files.
 PGID='$(id -g)' 			'g' 			'string'				s 			0			''		  group id - set MAMBO_GROUP_ID variable - will own bind mount created folder/files.
 "
@@ -565,7 +588,9 @@ type docker-compose 1>/dev/null 2>&1 && {
 	__manage_env_and_files
 }
 
-
+# set some environment variables at runtime
+export MAMBO_HOSTNAME="$(hostname)"
+__update_env_for_docker_compose "MAMBO_HOSTNAME"
 
 # set environment variables from command line
 [ "${MAMBO_USER_ID}" = "" ] && export MAMBO_USER_ID="${PUID}" \
@@ -577,15 +602,28 @@ type docker-compose 1>/dev/null 2>&1 && {
 __update_env_for_docker_compose "MAMBO_USER_ID"
 __update_env_for_docker_compose "MAMBO_GROUP_ID"
 
+[ ! "${DOMAIN}" = "" ] && export MAMBO_DOMAIN="${DOMAIN}"
+__update_env_for_docker_compose "MAMBO_DOMAIN"
+
 [ "${DAEMON}" = "1" ] && DAEMON="-d"
 
-case $DOMAIN in
+if [ "${DEBUG}" = "1" ]; then
+	VERBOSE="1"
+	[ "${LETS_ENCRYPT}" = "enable" ] && export LETS_ENCRYPT="debug"
+	__update_env_for_docker_compose "LETS_ENCRYPT"
+fi
+
+case $ACTION in
 	install )
+		;;
+	up|restart )
+		__set_mandatory_root_path_to_default
+		__check_mandatory_root_path
+		__check_lets_encrypt_settings
 		;;
 	* )
 		__set_mandatory_root_path_to_default
 		__check_mandatory_root_path
-		__check_lets_encrypt_settings
 		;;
 esac
 
@@ -593,7 +631,7 @@ esac
 # ------------- ENV ----------------------------
 
 
-case $DOMAIN in
+case $ACTION in
 	install )
 		echo "** Install requirements"
 		$STELLA_API get_features
