update

diff --git a/mambo b/mambo
--- a/mambo
+++ b/mambo
@@ -3,39 +3,40 @@ _CURRENT_FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 _CURRENT_RUNNING_DIR="$( cd "$( dirname "." )" && pwd )"
 . "${_CURRENT_FILE_DIR}"/stella-link.sh include
 
-DOCKER_COMPOSE_FILE="${STELLA_APP_ROOT}"/docker-compose.yml
-DOCKER_COMPOSE_FILE_GENERATED="${STELLA_APP_ROOT}"/docker-compose-gen.yml
-
-# Make '.env' docker-compose-file compatible for bash
-sed -e 's/^MAMBO_MEDIA_FOLDERS=\(.*\)$/MAMBO_MEDIA_FOLDERS=\"\1\"/' .env > "${STELLA_APP_ROOT}"/.env-bash
-. "${STELLA_APP_ROOT}"/.env-bash
-
-
-
-
-usage() {
-	echo "USAGE :"
-	echo "----------------"
-	echo "o-- general management :"
-	echo "L     env install|uninstall : deploy/undeploy this app"
-}
+DOCKER_COMPOSE_FILE_DEFAULT="${STELLA_APP_ROOT}/docker-compose.yml"
+DOCKER_COMPOSE_FILE_GENERATED="${STELLA_APP_ROOT}/docker-compose-gen.yml"
+ENV_FILE_DEFAULT="${STELLA_APP_ROOT}/env.default"
+# ".env" file are auto loader by docker-compose
+ENV_FILE_GENERATED="${STELLA_APP_ROOT}/.env"
+ENV_FILE_FOR_BASH_GENERATED="${STELLA_APP_ROOT}/env.bash"
+ENV_FILE_USER="${STELLA_APP_ROOT}/env.site"
 
 
-__add_volume_for_time() {
-	local __service_name="$1"
+__generate_files() {
+	__create_env_for_docker_compose
+	__create_env_for_bash
+	__set_docker_compose_file
 	
-	# create these volume only if they exists
-	[ -f "/etc/timezone" ] && yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "services.$1.volumes[+]" "/etc/timezone:/etc/timezone:ro"
-	[ -f "/etc/localtime" ] && yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "services.$1.volumes[+]" "/etc/localtime:/etc/localtime:ro"
+}
+
+
+__create_env_for_docker_compose() {
+	[ -f "${ENV_FILE_USER}" ] && cat "${ENV_FILE_DEFAULT}" "${ENV_FILE_USER}" > "${ENV_FILE_GENERATED}" \
+					|| cat "${ENV_FILE_DEFAULT}" > "${ENV_FILE_GENERATED}"
 
 }
 
+__create_env_for_bash() {
+	# Make '.env' docker-compose-file compatible for bash
+	sed -e 's/^MAMBO_MEDIA_FOLDERS=\(.*\)$/MAMBO_MEDIA_FOLDERS=\"\1\"/' "${ENV_FILE_GENERATED}" > "${ENV_FILE_FOR_BASH_GENERATED}"
+	. "${ENV_FILE_FOR_BASH_GENERATED}"
+}
 
 __set_docker_compose_file() {
 	rm -f "${DOCKER_COMPOSE_FILE_GENERATED}"
 
 	# copy original docker compose file
-	cp -f "${DOCKER_COMPOSE_FILE}" "${DOCKER_COMPOSE_FILE_GENERATED}"
+	cp -f "${DOCKER_COMPOSE_FILE_DEFAULT}" "${DOCKER_COMPOSE_FILE_GENERATED}"
 
 	__add_volume_for_time "organizr2"
 	__add_volume_for_time "ombi"
@@ -44,27 +45,86 @@ __set_docker_compose_file() {
 	__add_volume_for_time "tautulli"
 	__add_volume_for_time "calibreweb_books"
 	__add_volume_for_time "calibreweb_comics"
+
+
+	__add_service_direct_port_access
 }
 
-# Mambo path
-# Path must exists
-# Absolute path needed (cause of https://github.com/docker/compose/issues/6343)
-__set_default_path() {
- 	[ "${MAMBO_DATA_PATH}" = "" ] && export MAMBO_DATA_PATH="${STELLA_APP_WORK_ROOT}/data"
- 	[ "${MAMBO_DOWNLOAD_PATH}" = "" ] && export MAMBO_DOWNLOAD_PATH="${STELLA_APP_WORK_ROOT}/download"
- 	[ "${MAMBO_MEDIA_PATH}" = "" ] && export MAMBO_MEDIA_PATH="${STELLA_APP_WORK_ROOT}/media"
 
-	mkdir -p "${MAMBO_DATA_PATH}"
-	mkdir -p "${MAMBO_DOWNLOAD_PATH}"
-	mkdir -p "${MAMBO_MEDIA_PATH}"
+__add_volume_for_time() {
+	local __service_name="$1"
+	
+	# create these volumes only if files exists
+	[ -f "/etc/timezone" ] && yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "services.$1.volumes[+]" "/etc/timezone:/etc/timezone:ro"
+	[ -f "/etc/localtime" ] && yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "services.$1.volumes[+]" "/etc/localtime:/etc/localtime:ro"
 }
 
-# check if mambo have been installed
-type docker-compose 2>/dev/null && {
-	__set_default_path
-	__set_docker_compose_file
+__add_service_direct_port_access() {
+
+	for service in $(compgen -A variable | grep DIRECT_ACCESS_PORT_); do
+		port="${!service}"
+		if [ ! "${port}" = "" ]; then
+			service="${service#DIRECT_ACCESS_PORT_}"
+			service="${service,,}"
+			port_inside="$(yq r docker-compose.yml services.$service.expose[0])"
+			if [ ! "${port_inside}" = "" ]; then
+				echo "* Activate direct access to $service : mapping $port to $port_inside"
+				yq w -i "${DOCKER_COMPOSE_FILE_GENERATED}" "services.$service.ports[+]" "$port:$port_inside"
+			else
+				echo "* WARN : cannot activate direct access to $service throug $port. Unknow inside port to map to. Inside port must be declared as first port in expose section."
+			fi
+		fi
+	done
+}
+
+
+# Mambo mandatory root path
+# These paths can be defined in ENV_FILE_USER or by environment variable before launching mambo
+# If thery defined these path must exists and can be absolute or relative (dispite of https://github.com/docker/compose/issues/6343) - because we translate it to abs path in and reexport these vars in bash
+# If they are not defined some default values are assigned and path are created (only if default values is used - we are using docker to create with root and give permissions to the chooser user:group id)
+__set_mandatory_root_path_to_default() {
+	if [ "${MAMBO_DATA_PATH}" = "" ]; then
+	 	export MAMBO_DATA_PATH="${STELLA_APP_WORK_ROOT}/data"
+		docker run -it --rm -v "${STELLA_APP_WORK_ROOT}":"${STELLA_APP_WORK_ROOT}" bash:4.4.23 bash -c "mkdir -p "${MAMBO_DATA_PATH}" && chown ${MAMBO_USER_ID}:${MAMBO_GROUP_ID} "${MAMBO_DATA_PATH}""
+	else
+		# TODO 1 chown ${MAMBO_USER_ID}:${MAMBO_GROUP_ID} "${MAMBO_DATA_PATH}" ? if exists ? or do it in service_init ?
+		export MAMBO_DATA_PATH="$($STELLA_API rel_to_abs_path "${MAMBO_DATA_PATH}" "${STELLA_APP_ROOT}")"
+		# TODO 2 create dir in all cases ? not only in case we are using default values
+	fi
+	if [ "${MAMBO_DOWNLOAD_PATH}" = "" ]; then
+	 	export MAMBO_DOWNLOAD_PATH="${STELLA_APP_WORK_ROOT}/download"
+		docker run -it --rm -v "${STELLA_APP_WORK_ROOT}":"${STELLA_APP_WORK_ROOT}" bash:4.4.23 bash -c "mkdir -p "${MAMBO_DOWNLOAD_PATH}" && chown ${MAMBO_USER_ID}:${MAMBO_GROUP_ID} "${MAMBO_DOWNLOAD_PATH}""
+	fi
+	if [ "${MAMBO_MEDIA_PATH}" = "" ]; then
+	 	export MAMBO_MEDIA_PATH="${STELLA_APP_WORK_ROOT}/media"
+		docker run -it --rm -v "${STELLA_APP_WORK_ROOT}":"${STELLA_APP_WORK_ROOT}" bash:4.4.23 bash -c "mkdir -p "${MAMBO_MEDIA_PATH}" && chown ${MAMBO_USER_ID}:${MAMBO_GROUP_ID} "${MAMBO_MEDIA_PATH}""
+	fi
+}
+
+__check_mandatory_root_path() {
+	# test if mandatory root path exists
+	[ ! -d "${MAMBO_DATA_PATH}" ] && echo "* ERROR : Mandatory data root path [${MAMBO_DATA_PATH}] do not exist" && exit 1
+	[ ! -d "${MAMBO_DOWNLOAD_PATH}" ] && echo "* ERROR : Mandatory download root path [${MAMBO_DOWNLOAD_PATH}] do not exist" && exit 1
+	[ ! -d "${MAMBO_MEDIA_PATH}" ] && echo "* ERROR : Mandatory media root path [${MAMBO_MEDIA_PATH}] do not exist" && exit 1
+}
+
+# check if mambo have been installed and generate all files
+type docker-compose 1>/dev/null 2>&1 && {
+	__generate_files
  	MAMBO_SERVICES_LIST="$(echo $(docker-compose config --services | grep -v _disable))"
 } || MAMBO_SERVICES_LIST=" "
+
+
+usage() {
+	echo "USAGE :"
+	echo "----------------"
+	echo "o-- general management :"
+	echo "L     install|uninstall : deploy/undeploy this app"
+	echo "L     up/down : "
+	echo "L     status : "
+	echo "L     logs : "
+	echo "L     set : "
+}
 
 # COMMAND LINE -----------------------------------------------------------------------------------
 PARAMETERS="
@@ -73,22 +133,27 @@ TARGET=												'action' 					a				'${MAMBO_SERVICES_LIST}'	'0' 'Target.'
 "
 OPTIONS="
 FORCE=''				   'f'		  ''					b			0		'1'					  Force.
-PUID='$(id -u)' 			'g' 			'string'				s 			0			''		  user id - will own bind mount created folder/files.
-PGID='$(id -g)' 			'u' 			'string'				s 			0			''		  group id - will own bind mount created folder/files.
+DAEMON=''				   'd'		  ''					b			0		'1'					  Daemon mode.
+PUID='$(id -u)' 			'g' 			'string'				s 			0			''		  user id - set MAMBO_USER_ID variable - will own bind mount created folder/files.
+PGID='$(id -g)' 			'u' 			'string'				s 			0			''		  group id - set MAMBO_GROUP_ID variable - will own bind mount created folder/files.
 "
 $STELLA_API argparse "$0" "$OPTIONS" "$PARAMETERS" "$STELLA_APP_NAME" "$(usage)" "EXTRA_ARG ARG" "$@"
 
 #-------------------------------------------------------------------------------------------
-# get environment variables
+
+# set environment variables from command line
 [ "${MAMBO_USER_ID}" = "" ] && export MAMBO_USER_ID="${PUID}" \
 								|| export MAMBO_USER_ID="${MAMBO_USER_ID}"
 
 [ "${MAMBO_GROUP_ID}" = "" ] && export MAMBO_GROUP_ID="${PGID}" \
 								|| export MAMBO_GROUP_ID="${MAMBO_GROUP_ID}"
 
-# domain name - '.*' stands for any domain name
-[ "${MAMBO_DOMAIN}" = "" ] && export MAMBO_DOMAIN='.*' \
-								|| export MAMBO_DOMAIN="${MAMBO_DOMAIN}"
+
+
+[ "${DAEMON}" = "1" ] && DAEMON="-d"
+
+__set_mandatory_root_path_to_default
+__check_mandatory_root_path
 
 
 # ------------- ENV ----------------------------
@@ -105,16 +170,18 @@ case $DOMAIN in
 	;;
 
 	set )
-		__set_docker_compose_file
+		echo "* Files have been generated."
 	;;
 	up )
-		#__set_docker_compose_file
-		docker-compose -f "${DOCKER_COMPOSE_FILE_GENERATED}" up ${TARGET:-mambo}
-		docker-compose -f "${DOCKER_COMPOSE_FILE_GENERATED}" logs service_init
+		docker-compose -f "${DOCKER_COMPOSE_FILE_GENERATED}" up ${DAEMON} ${TARGET:-mambo}
+		if [ "${DAEMON}" = "" ]; then
+			[ "${TARGET}" = "" ] && docker-compose -f "${DOCKER_COMPOSE_FILE_GENERATED}" logs service_init
+		else
+			docker-compose -f "${DOCKER_COMPOSE_FILE_GENERATED}" logs service_init
+		fi
 	;;
 
 	down )
-		#__set_docker_compose_file
 		case "${TARGET}" in
 		"") 
 			docker-compose -f "${DOCKER_COMPOSE_FILE_GENERATED}" down -v 
@@ -130,7 +197,7 @@ case $DOMAIN in
 	;;
 
 	logs )
-		docker-compose -f "${DOCKER_COMPOSE_FILE_GENERATED}" logs -t  ${TARGET}
+		docker-compose -f "${DOCKER_COMPOSE_FILE_GENERATED}" logs -t ${TARGET}
 	;;
 esac
 
