update

diff --git a/mambo b/mambo
--- a/mambo
+++ b/mambo
@@ -74,7 +74,7 @@ usage() {
 	echo "o-- commands :"
 	echo "L     install : deploy this app."
 	echo "L     init plex [--claim] : init plex service. Do it at least once before launch for plex. - will stop plex --claim : will force to claim server even it is already registred"
-	echo "L     init [sabnzbd|medusa|nzbtomedia] : init all or one services. Will stop service if running and configure some default settings without modifying other settings."
+	echo "L     init [sabnzbd|medusa|nzbtomedia|transmission|organizr2] : init all or one services. Will stop service if running and configure some default settings without modifying other settings."
     echo "L     up [service [-b]] [--module module] [--plugin plugin] [--freeport]: launch all available services or one service"
 	echo "L     down [service] [--mods mod-name] [--all]: down all services or one service. Except shared internal service when in shared mode (--all force stop shared service)."
 	echo "L     restart [service] [--module module] [--plugin plugin] [--freeport]: restart all services or one service. (same action than up & down)"
@@ -88,7 +88,8 @@ usage() {
 	echo "L     scripts exec <script> : exec a script."
 	echo "o-- various commands :"
 	echo "L		cert <path> --domain=<domain> : generate self signed certificate for a domain into a current host folder."
-    echo "L		letsencrypt rm : delete generated letsencrypt cert."
+    echo "L		letsencrypt rm : delete generated letsencrypt cert [WARN : delete certs will regenerate request to letsencrypt. Too much requests and you may be banned for a time]"
+	echo "L		letsencrypt logs : follow letsencrypt actions"
     echo "L		auth sync : sync authorization information between organizr2 and traefik."
     echo "L		auth enable|disable : temporary enable|disable organizr2 until next up/down. To be permanent use ORGANIZR2_AUTHORIZATION variable"
 
@@ -140,6 +141,13 @@ case ${ACTION} in
     ;;
     init )
         __action_done_by_mambo="1"
+    ;;
+    update )
+        case ${TARGET} in
+            organizr2 )
+                __action_done_by_mambo="1"
+            ;;
+        esac
     ;;
 
 esac
@@ -208,6 +216,14 @@ fi
     
 # mambo actions
 case ${ACTION} in
+    update )
+            case ${TARGET} in
+                organizr2 )
+                    __tango_log "INFO" "mambo" "Update service Organizr2"
+                    __organizr2_update
+                ;;
+            esac
+    ;;
     init )
         case ${TARGET} in
             plex )
@@ -232,6 +248,10 @@ case ${ACTION} in
                 __tango_log "INFO" "mambo" "Init service organizr2 (instance : $ORGANIZR2_INSTANCE)"
                 __organizr2_init
             ;;
+            transmission )
+                __tango_log "INFO" "mambo" "Init service transmission"
+                __transmission_init
+            ;;
             "" )
                 __tango_log "INFO" "mambo" "Init service Plex"
                 __plex_init
@@ -242,6 +262,9 @@ case ${ACTION} in
                 __tango_log "INFO" "mambo" "Init service sabnzbd"
                 __sabnzbd_init
                 [ $? -ne 0 ] && __tango_log "ERROR" "mambo" "Error while configuring sabnzbd" && exit 1
+                __tango_log "INFO" "mambo" "Init service transmission"
+                __transmission_init
+                [ $? -ne 0 ] && __tango_log "ERROR" "mambo" "Error while configuring transmission" && exit 1
                 __tango_log "INFO" "mambo" "Init service medusa"
                 # we compute this only if we need it because it take times
                 export PLEX_AUTH_TOKEN="$(__get_plex_x_plex_auth_token ${PLEX_USER} ${PLEX_PASSWORD})"
